language: php

php:
  - 5.3

before_script:
  - pear install PHP_CodeSniffer-1.5.3
  - phpenv config-add .travis.ini
  - phpenv rehash

script:
  - phpcs --report=full --extensions=php -p -w --standard=.build/phpcs/Joomla src/
