language: php

php:
  - 5.3

before_script:
  # Composer
  - composer self-update
  - composer update

  # Cloning Joomla Coding standards
  - git clone https://github.com/joomla/coding-standards.git .tmp/Joomla/

script:
  - vendor/bin/phpcs --report=summary --extensions=php -p -n --standard=.tmp/Joomla src/
